---
  version: '2'
  services:
    mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
    app:
      build: .
      command: /usr/bin/dumb-init -- ./run.sh
      volumes:
        - ./app:/app
      ports:
        - "5678:5678"
      depends_on:
        - mongodb
      links:
        - mongodb
      environment:
        - MONGODB_NAME=development
      env_file:
        - surveyer.env    
  volumes:
    mongodb: